### ISSUE TITLE
Install Android Studio/IntelliJ with AndroidSdk (each teammate)

### ISSUE THREAD

**Issue by mateusz-ant** [slonka/pushegro-client#3]
Install:
- Android Studio/IntelliJ
- SDK for Android 4.1.2 and for your phone version
- Google Play Services

Make sure that:
- your android emulator works and you can successfully deploy apps on it
- you can deploy apps on your android phone from IDE

Each teammate is kindly asked to add a comment that they accomplished this task.

**Comment by slonka** [comment]
Done

**Comment by gmiejski** [comment]
DONE

**Comment by mateusz-ant** [comment]
Done
